export const apiUrls = {
  login: "login",
  signUp: "register",
  verifyOtp: "verify-otp",
  getUsers: "users",
  updateUser: "user",
  changePassword: "user/change-password",
  offers: "offers",
  carrers: "careers",
  carrersStatus: "careersstatus",
  courses: "courses",
  category: "category",
  lessons: "lessons",
  reviews: "reviews",
};
